# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_document_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='apertura',
            field=models.TextField(default='8'),
            preserve_default=False,
        ),
    ]
