# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_document_apertura'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dfocal',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='edsoft',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
