# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20161014_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='tiempexp',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
    ]
