# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_document_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='author',
            new_name='fotografo',
        ),
    ]
