# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20161107_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='foto',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
    ]
